name: Run Burgers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-burgers:
    name: Run Burgers
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - uses: julia-actions/julia-buildpkg@v1

      - run: |
          julia --project make_with_output.jl

      # The non-output version has been committed in the meantime
      - run: |
          git pull

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run Burgers notebook
